[0m13:32:44.509810 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103fbf040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10562e050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10562dc90>]}


============================== 13:32:44.513027 | 1f3554c9-5c35-4c84-ae16-54c2f8cdaec0 ==============================
[0m13:32:44.513027 [info ] [MainThread]: Running with dbt=1.7.2
[0m13:32:44.513415 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt -p vscode_pytest --collect-only --color=yes', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:32:44.513812 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:32:44.515266 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.020369291, "process_user_time": 1.221274, "process_kernel_time": 0.141617, "process_mem_max_rss": "114507776", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:32:44.515663 [debug] [MainThread]: Command `cli run` failed at 13:32:44.515570 after 0.02 seconds
[0m13:32:44.515919 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103fbf040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10562e200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10562e620>]}
[0m13:32:44.516168 [debug] [MainThread]: Flushing usage events
[0m13:35:07.162568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11121eda0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112adb100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112ada980>]}


============================== 13:35:07.165763 | cf7136ec-ab69-4f21-8f06-39d4710a8eb2 ==============================
[0m13:35:07.165763 [info ] [MainThread]: Running with dbt=1.7.2
[0m13:35:07.166150 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt --rootdir /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb --color=yes', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:35:07.166544 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:35:07.168046 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.018493293, "process_user_time": 1.158713, "process_kernel_time": 0.10022, "process_mem_max_rss": "112623616", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:35:07.168466 [debug] [MainThread]: Command `cli run` failed at 13:35:07.168367 after 0.02 seconds
[0m13:35:07.168743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11121eda0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112adb250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112adb700>]}
[0m13:35:07.169010 [debug] [MainThread]: Flushing usage events
[0m13:37:19.138367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10601cbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202a6e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202a6bc0>]}


============================== 13:37:19.141505 | 6a4f509c-2288-42bc-bef8-e2d077cc0d2a ==============================
[0m13:37:19.141505 [info ] [MainThread]: Running with dbt=1.7.2
[0m13:37:19.141909 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt --rootdir /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb --color=yes', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:37:19.142300 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:37:19.143528 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.016414583, "process_user_time": 1.15739, "process_kernel_time": 0.097547, "process_mem_max_rss": "113688576", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:37:19.143867 [debug] [MainThread]: Command `cli run` failed at 13:37:19.143782 after 0.02 seconds
[0m13:37:19.144110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10601cbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202a7190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202a7520>]}
[0m13:37:19.144345 [debug] [MainThread]: Flushing usage events
[0m04:41:49.764943 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106dd5540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f990f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f988e0>]}


============================== 04:41:49.768664 | c9d149bd-3789-4dca-9126-4613a41a142f ==============================
[0m04:41:49.768664 [info ] [MainThread]: Running with dbt=1.7.2
[0m04:41:49.769019 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:41:49.769400 [info ] [MainThread]: dbt version: 1.7.2
[0m04:41:49.769610 [info ] [MainThread]: python version: 3.10.12
[0m04:41:49.769809 [info ] [MainThread]: python path: /Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/bin/python
[0m04:41:49.770006 [info ] [MainThread]: os info: macOS-14.1.1-arm64-arm-64bit
[0m04:41:49.770356 [error] [MainThread]: Encountered an error:
local variable 'summary_message' referenced before assignment
[0m04:41:49.771494 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 444, in debug
    results = task.run()
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/task/debug.py", line 123, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/task/debug.py", line 208, in _load_profile
    profile_names, summary_message = self._choose_profile_names()
  File "/Users/ajsteers/Library/Caches/pypoetry/virtualenvs/source-dbt-duckdb-wArIZlx6-py3.10/lib/python3.10/site-packages/dbt/task/debug.py", line 283, in _choose_profile_names
    return profiles, summary_message
UnboundLocalError: local variable 'summary_message' referenced before assignment

[0m04:41:49.772528 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.018898625, "process_user_time": 1.171018, "process_kernel_time": 0.122501, "process_mem_max_rss": "98172928", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m04:41:49.772857 [debug] [MainThread]: Command `dbt debug` failed at 04:41:49.772780 after 0.02 seconds
[0m04:41:49.773070 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106dd5540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f996f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f990c0>]}
[0m04:41:49.773282 [debug] [MainThread]: Flushing usage events
[0m04:42:09.981453 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102bd2a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052991b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105298520>]}


============================== 04:42:09.984428 | 3d39e88c-f09e-4dde-a50c-2149786837a9 ==============================
[0m04:42:09.984428 [info ] [MainThread]: Running with dbt=1.7.2
[0m04:42:09.984793 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt compile', 'send_anonymous_usage_stats': 'True'}
[0m04:42:09.985162 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m04:42:09.986213 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.017623916, "process_user_time": 1.154746, "process_kernel_time": 0.126914, "process_mem_max_rss": "99926016", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m04:42:09.986603 [debug] [MainThread]: Command `dbt compile` failed at 04:42:09.986517 after 0.02 seconds
[0m04:42:09.986850 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102bd2a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052996c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105299780>]}
[0m04:42:09.987077 [debug] [MainThread]: Flushing usage events
[0m05:15:11.819197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10304f580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051c9420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051c8ee0>]}


============================== 05:15:11.822746 | aab4fd43-747f-4cf6-b74b-eeccc1989b88 ==============================
[0m05:15:11.822746 [info ] [MainThread]: Running with dbt=1.7.2
[0m05:15:11.823128 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/ajsteers/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt source freshness', 'send_anonymous_usage_stats': 'True'}
[0m05:15:11.823492 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ajsteers/Source/airbyte/airbyte-integrations/connectors/source-dbt-duckdb/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:15:11.824626 [debug] [MainThread]: Resource report: {"command_name": "freshness", "command_wall_clock_time": 0.016891416, "process_user_time": 1.148753, "process_kernel_time": 0.117099, "process_mem_max_rss": "99172352", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m05:15:11.825076 [debug] [MainThread]: Command `dbt source freshness` failed at 05:15:11.824988 after 0.02 seconds
[0m05:15:11.825325 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10304f580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051c98a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051c9990>]}
[0m05:15:11.825587 [debug] [MainThread]: Flushing usage events
